### ISSUE TITLE
请问所给出的BERT-fintune-MFT的权重使用的huggingface模块是哪个，直接使用BERT初始化会导致有最后的权重没有被用到？

### ISSUE THREAD

**Issue by Liucc2119** [gingasan/lemon#1]

**Comment by gingasan** [comment]
你好，使用的是我的autocsc.py里的AutoCSCfinetune，这个就是基于huggingface BERT写的。

如果你觉得我的代码有更好的实现，也欢迎联系。

----- 原始邮件 -----
发件人: "Liucc2119" ***@***.***>
收件人: "gingasan/lemon" ***@***.***>
抄送: "Subscribed" ***@***.***>
发送时间: 星期日, 2023年 7 月 23日 下午 8:38:14
主题: [gingasan/lemon] 请问所给出的BERT-fintune-MFT的权重使用的huggingface模块是哪个，直接使用BERT初始化会导致有最后的权重没有被用到？ (Issue #1)

-- 
Reply to this email directly or view it on GitHub:
https://github.com/gingasan/lemon/issues/1

**Comment by gingasan** [comment]
Hi, thank you for your attention. We are releasing a new model, which is optimized based on rephrasing language modeling. Welcome to try it out~

----- 原始邮件 -----
发件人: "伍鸿秋" ***@***.***>
收件人: "gingasan" ***@***.***>
发送时间: 星期日, 2023年 7 月 23日 下午 8:46:17
主题: Re: [gingasan/lemon] 请问所给出的BERT-fintune-MFT的权重使用的huggingface模块是哪个，直接使用BERT初始化会导致有最后的权重没有被用到？ (Issue #1)

你好，使用的是我的autocsc.py里的AutoCSCfinetune，这个就是基于huggingface BERT写的。

如果你觉得我的代码有更好的实现，也欢迎联系。

----- 原始邮件 -----
发件人: "Liucc2119" ***@***.***>
收件人: "gingasan/lemon" ***@***.***>
抄送: "Subscribed" ***@***.***>
发送时间: 星期日, 2023年 7 月 23日 下午 8:38:14
主题: [gingasan/lemon] 请问所给出的BERT-fintune-MFT的权重使用的huggingface模块是哪个，直接使用BERT初始化会导致有最后的权重没有被用到？ (Issue #1)

-- 
Reply to this email directly or view it on GitHub:
https://github.com/gingasan/lemon/issues/1
