### ISSUE TITLE
关于实验结果的复现

### ISSUE THREAD

**Issue by TheJun1999** [gingasan/lemon#2]
**_论文结果1_：**
![image](https://github.com/gingasan/lemon/assets/76474092/f319744f-e9d9-43b8-9072-e589ae9108b6)
**_论文结果2_：**
![image](https://github.com/gingasan/lemon/assets/76474092/5b3d3d1a-f001-4ec3-aba0-59c8c912d0cf)
我的实验：
![image](https://github.com/gingasan/lemon/assets/76474092/982218a5-4de6-4b7a-ab19-5b2d1a778b5f)
问题1：上图的结果是我直接使用如下图的softmaskedbert模型权重（作者发布的）得到的，请问这是论文中提到LEMON（即**论文结果1**）中的SIGHAN的结果吗:？
![image](https://github.com/gingasan/lemon/assets/76474092/07d59ce7-0496-489f-a387-2393823149b4)
问题2：请问**论文结果2**SIGHAN15中使用softmaskedbert的结果是如何实现的，和**论文结果1**的实现过程有什么区别？
感谢作者的回答

**Comment by gingasan** [comment]
你好，

1. 开源的权重对应的是论文结果1：
这里的我们没有在sighan的训练集上训练过，结果是zero-shot下的。我上传的模型就是论文里汇报的模型，你的结果也是53.4，和文章里一样～

2. 论文结果2中的结果是有监督微调：
即在sighan对应的训练集上进行了微调，关于sighan的微调一般分为两个阶段，我的文章里有写细节，你可以参考一下。

3. 论文结果1和2的区别：
在1里，我们首先基于中文维基百科的语料，利用混淆集构造训练对（这是不包含任何人工标注的）。随后bert-base-chinese在上面训练，结束之后直接在lemon和sighan的测试集上测试。
在2里，在对应的训练集上微调bert-base-chinese。

**Comment by TheJun1999** [comment]
> 你好，
> 
> 1. 开源的权重对应的是论文结果1：
>    这里的我们没有在sighan的训练集上训练过，结果是zero-shot下的。我上传的模型就是论文里汇报的模型，你的结果也是53.4，和文章里一样～
> 2. 论文结果2中的结果是有监督微调：
>    即在sighan对应的训练集上进行了微调，关于sighan的微调一般分为两个阶段，我的文章里有写细节，你可以参考一下。
> 3. 论文结果1和2的区别：
>    在1里，我们首先基于中文维基百科的语料，利用混淆集构造训练对（这是不包含任何人工标注的）。随后bert-base-chinese在上面训练，结束之后直接在lemon和sighan的测试集上测试。
>    在2里，在对应的训练集上微调bert-base-chinese。

十分感谢你的回复！

问题1：根据你的解答，我的理解是论文结果2中的训练集是SIGHAN15的训练集和WANG的270K条数据增强训练集合并得到的，微调之前BERT的权重使用的是huggingface上的bert-base-chinese权重（即没有经过混淆集构造训练对的预训练），不知道这样的理解是否准确？
问题2：
![image](https://github.com/gingasan/lemon/assets/76474092/ad98ca13-2ae9-4deb-8c58-c2a035535cbb)
如上图发布的代码中self.post_init()这个方法似乎没有被定义，无法被调用，报错信息如下，我的解决方法是对这行代码进行注释，请问这样的处理是否符合规范？是否有更好的方法进行解决？
![image](https://github.com/gingasan/lemon/assets/76474092/7df65aa4-1a02-4129-8e91-a8960972b055)

**Comment by gingasan** [comment]
嗯你的理解正确。

self.post_init()这是个huggingface transformers里的自带初始化，BertPretrainedModel下的模型应该都能调用。https://github.com/huggingface/transformers/blob/main/src/transformers/models/bert/modeling_bert.py#L1302

你这里报错我猜测可能是版本的问题，但注释掉也没有影响。

**Comment by gingasan** [comment]
Hi, thank you for your attention. We are releasing a new model, which is optimized based on rephrasing language modeling. Welcome to try it out~

**Comment by zzxxa** [comment]
大佬，请问ECSpell数据集也是两阶段训练的么？还是说ECSpell的结果是没有用Wang271k的？

**Comment by gingasan** [comment]
就一阶段微调，没有用额外的数据。

----- 原始邮件 -----
发件人: "zzxxa" ***@***.***>
收件人: "gingasan/lemon" ***@***.***>
抄送: "gingasan" ***@***.***>, "State change" ***@***.***>
发送时间: 星期四, 2025年 6 月 12日 上午 10:14:55
主题: Re: [gingasan/lemon] 关于实验结果的复现 (Issue #2)

zzxxa left a comment (gingasan/lemon#2)

大佬，请问ECSpell数据集也是两阶段训练的么？还是说ECSpell的结果是没有用Wang271k的？

**Comment by zzxxa** [comment]
这是来自QQ邮箱的假期自动回复邮件。收到了你的邮件,我会尽快查看,谢谢~~~

**Comment by zzxxa** [comment]
> 就一阶段微调，没有用额外的数据。
> […](#)

谢谢回复，我用两阶段，在Law上f1跑到90%左右，我都怀疑自己了-_-
