### ISSUE TITLE
关于微调数据格式问题

### ISSUE THREAD

**Issue by zidong-onepiece1** [gingasan/lemon#3]
您好！
       想请教一下。在数据预处理阶段，看到了以下处理代码
```
# a) xxx
# b) separate Chinese characters from each other by spaces;
# c) xxx
...
src ,trg = line.strip().split("\t")
lines.append((src.split(), trg.split()))
...
```
问题1：注释b的含义是什么
问题2：输入数据的格式是怎样的，例如如果是 `line = "今天天起很好\t今天天气很好"`，那么为什么要做`src.split()`和'trg.split()'？

**Comment by gingasan** [comment]
你好，

我是这个意思，data里先分好词:

今天天起很好\t今天天气很好 -> 今 天 天 起 很 好\t今 天 天 气 很 好

----- 原始邮件 -----
发件人: "zzd" ***@***.***>
收件人: "gingasan/lemon" ***@***.***>
抄送: "Subscribed" ***@***.***>
发送时间: 星期二, 2023年 8 月 15日 下午 5:35:47
主题: [gingasan/lemon] 关于微调数据格式问题 (Issue #3)

您好！
       想请教一下。在数据预处理阶段，看到了以下处理代码
```
# a) xxx
# b) separate Chinese characters from each other by spaces;
# c) xxx
...
src ,trg = line.strip().split("\t")
lines.append((src.split(), trg.split()))
...
```
问题1：注释b的含义是什么
问题2：输入数据的格式是怎样的，例如如果是 `line = "今天天起很好\t今天天气很好"`，那么为什么要做`src.split()`和'trg.split()'？



-- 
Reply to this email directly or view it on GitHub:
https://github.com/gingasan/lemon/issues/3

**Comment by zidong-onepiece1** [comment]
非常感谢！另外建议您可以在readme中贴上autocsc.py中支持的多种纠错模型对应的paper和code地址

**Comment by gingasan** [comment]
Hi, thank you for your attention. We are releasing a new model, which is optimized based on rephrasing language modeling. Welcome to try it out~
