### ISSUE TITLE
论文中baichuan-7B 是Base还是Chat?

### ISSUE THREAD

**Issue by macanv** [gingasan/lemon#9]
老师好，请问论文中，使用baichuan2-7B模型，是使用Chat还是Base模型进行微调的呀？
另外，LLM结果是使用什么方式进行评测的，我发现Baichuan2-7/13B  Chat 使用同一个prompt在zero/few-shot下，模型回答格式不规范，一直在变，不知道老师有木有遇到过这种问题。
期待回复。

**Comment by Claude-Liu** [comment]
您好，
1. 论文中使用的是微调baichuan2-7B base得到的。具体代码参考https://github.com/gingasan/lemon/blob/main/sft_csc.py。
2. "LLM结果"是指论文中ChatGPT-10shot吗？这个结果是通过query gpt3.5的api得到的。代码可以参考https://github.com/Claude-Liu/ReLM/blob/main/utils/query_chatgpt.py。
3. “我发现Baichuan2-7/13B Chat 使用同一个prompt在zero/few-shot下，模型回答格式不规范，一直在变” 这个应该可以通过指令微调解决。

**Comment by macanv** [comment]
谢谢老师
